# This file was generated by GoReleaser. DO NOT EDIT.
cask "diffs" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "74e54ca62f52b6d6edf478b3858b83f7d9c69952cfc245594d33ac2a6bab2f88"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
    on_arm do
      sha256 "0c374425607e67769fc27ce5f0dabdd730e14d9da2e60a6ed03dc21801c0d5de"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "f0ffefbc2dca97fdba6ae6cc04e257453dbecfa621baa3d7d3f60e385e5bb313"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
    on_arm do
      sha256 "4ad2fa21e4409aa5ed12a6144cd459f4323d86dd0acc5d7d68519b36f58bfaed"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
  end

  name "diffs"
  desc "Fast, beautiful diffs on the Go"
  homepage "https://github.com/imfing/diffs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diffs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/diffs"]
    end
  end

  # No zap stanza required

end
