# This file was generated by GoReleaser. DO NOT EDIT.
cask "diffs" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "15f4b0e5dd00854690d7d5ff853c2b9986551ccd1e7e25553f87550e7bae1056"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
    on_arm do
      sha256 "65a59b72d6ea5924f0d4824163dc400f5014c053309ccf7e4e0370e184a0465a"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "22c8044726dfd7fcd134cd67dd95b5a8229045f644a3e9e8dcd9649d46afe3c5"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
    on_arm do
      sha256 "c9da6a48128c23b1dc1f1731d651864fa2fb41f50a81832878c8c0aaceb32e4f"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
  end

  name "diffs"
  desc "Fast, beautiful diffs on the Go"
  homepage "https://github.com/imfing/diffs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diffs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/diffs"]
    end
  end

  # No zap stanza required

end
