# This file was generated by GoReleaser. DO NOT EDIT.
cask "diffs" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "9fadb45cd9d7de4742fd4943f718329e1509a130eee41299f6ea0a6b8c826d16"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
    on_arm do
      sha256 "b0508489184feb2c07e7a574099da3892c0d8cd73b45c3f9d0edb2d906a8bc6e"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef6a4b3606e3e0c19d3223e21f6e00ec166ad33a2b056b05d6040ffd5b761f02"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_linux_amd64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
    on_arm do
      sha256 "09088cb9bd6f82d719a94572447770dad5f3cd5f50f66fa881f31e9bf9691cda"
      url "https://github.com/imfing/diffs-cli/releases/download/v#{version}/diffs_#{version}_linux_arm64.tar.gz",
        verified: "github.com/imfing/diffs-cli/"
    end
  end

  name "diffs"
  desc "Fast, beautiful diffs on the Go"
  homepage "https://github.com/imfing/diffs-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diffs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/diffs"]
    end
  end

  # No zap stanza required

end
