# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diffs < Formula
  desc "Fast, beautiful diffs on the Go"
  homepage "https://github.com/imfing/diffs-cli"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imfing/diffs-cli/releases/download/v0.1.3/diffs_0.1.3_darwin_amd64.tar.gz"
      sha256 "bb896e3c458e3b2c2aeed34065494ad012e5ea3547059f55b71b336c16b04117"

      define_method(:install) do
        bin.install "diffs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imfing/diffs-cli/releases/download/v0.1.3/diffs_0.1.3_darwin_arm64.tar.gz"
      sha256 "d507a04fb8c972e8b58d1738fe2d8c9f32a74e896439d6b46d433c5ac2a6bcf2"

      define_method(:install) do
        bin.install "diffs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/imfing/diffs-cli/releases/download/v0.1.3/diffs_0.1.3_linux_amd64.tar.gz"
      sha256 "b9c1db8a8458a074fa3609c0f8348fefc5726b82b01732cc26012b35a0bedb6f"
      define_method(:install) do
        bin.install "diffs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imfing/diffs-cli/releases/download/v0.1.3/diffs_0.1.3_linux_arm64.tar.gz"
      sha256 "804e8939fe496eaafc98b4e37251632e8c5e39296d4736deddc7ad18ef5459ae"
      define_method(:install) do
        bin.install "diffs"
      end
    end
  end

  test do
    assert_match "Review local diffs", shell_output("#{bin}/diffs --help")
  end
end
