# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gptui < Formula
  desc "Terminal UI for GPT."
  homepage "https://github.com/imfing/gptui"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imfing/gptui/releases/download/v0.0.2/gptui_Darwin_x86_64.tar.gz"
      sha256 "e7a2bda242576a41420b087caeb93331220a181781590f73dbc4fa5e7bf4fe5f"

      def install
        bin.install "gptui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imfing/gptui/releases/download/v0.0.2/gptui_Darwin_arm64.tar.gz"
      sha256 "2e655fdac460795b133abbb7c15a0eb2d6cdd0274e2102c7de60a9282743a4d1"

      def install
        bin.install "gptui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imfing/gptui/releases/download/v0.0.2/gptui_Linux_arm64.tar.gz"
      sha256 "5c9c4dc0cd5350523d2d0759e498ff4ded18a88bc3eaaf609a3f0efc9f7df724"

      def install
        bin.install "gptui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/imfing/gptui/releases/download/v0.0.2/gptui_Linux_x86_64.tar.gz"
      sha256 "8720c60d24b79210923908f9915053bbc6e6e140b2daa04ba9de5e7f120c140f"

      def install
        bin.install "gptui"
      end
    end
  end
end
